### ISSUE TITLE
Default values not populating when file opened

### ISSUE THREAD

**Issue by Adam--R** [zaro/pdf-metadata-editor#1]
Thank you for sharing this program!  It has the potential to save me a lot of time - I really appreciate your efforts.  I'm having an issue with the default values.  I've gone into settings and entered in the values that I would like each of my files to have, but when I open a .pdf in the editor, the values are always blank; they never get the default values that I have filled in.  When I go edit the default values again, my entries are stored there, they just don't get transferred to each file.

Thank you,
Adam

**Comment by zaro** [comment]
Did you download it yesterday ?
Yesterday I have mistakenly uploaded older version, having this bug, please download and try again and see if the problem persists.

**Comment by Adam--R** [comment]
I downloaded it yesterday from your blog.  It is the version with the installer.  I went ahead and tried the extract and run zip, and that seemed to have the same issue.

Thank you,
Adam

Adam Romary
aromary@collegiateschool.org<mailto:cmera@collegiateschool.org>
Science Teacher, Collegiate School
260 West 78th Street, New York, NY 10024
[collegiate logo]
________________________________

**Comment by zaro** [comment]
Ok. Did you try to download it again today? I uploaded new version this
morning.

**Comment by zaro** [comment]
Just uploaded 1.1.0. It should work, if there are still problems, reopen the issue.
