### ISSUE TITLE
Unrecognized characters from PDF metadata

### ISSUE THREAD

**Issue by eikoni** [zaro/pdf-metadata-editor#10]
Hi,
Error with this file :
[test.pdf](https://github.com/zaro/pdf-metadata-editor/files/596834/test.pdf)
It returns :
![snap 2016-11-17 at 09 07 39](https://cloud.githubusercontent.com/assets/11945427/20381000/a478df50-aca5-11e6-8160-defc03f09cc6.png)

Thanks.
E.

**Comment by zaro** [comment]
The metadata indeed contains invalid XML Entities :

This is the raw XML metadata from the document( you can see it foe yourself by opening the PDF with text editor, and look around line 45):

`
<x:xmpmeta xmlns:x='adobe:ns:meta/' x:xmptk='XMP toolkit 2.9.1-13, framework 1.6'>
<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#' xmlns:iX='http://ns.adobe.com/iX/1.0/'>
<rdf:Description rdf:about='c9784ce1-aef7-11e6-0000-ef37108bddb&#1;8?&#13;&#4;2016-11-17T09:02:49+01:00&apos; &#16;-L&#13;&#4;,&#2;@&#16;&#4;' xmlns:pdf='http://ns.adobe.com/pdf/1.3/'><pdf:Producer>GPL Ghostscript 9.04</pdf:Producer>
<pdf:Keywords>()</pdf:Keywords>
</rdf:Description>
<rdf:Description rdf:about='c9784ce1-aef7-11e6-0000-ef37108bddb&#1;8?&#13;&#4;2016-11-17T09:02:49+01:00&apos; &#16;-L&#13;&#4;,&#2;@&#16;&#4;' xmlns:xmp='http://ns.adobe.com/xap/1.0/'><xmp:ModifyDate>2016-11-17T09:02:49+01:00</xmp:ModifyDate>
<xmp:CreateDate>2016-11-17T09:02:49+01:00</xmp:CreateDate>
<xmp:CreatorTool>PDFCreator Version 1.2.3</xmp:CreatorTool></rdf:Description>
<rdf:Description rdf:about='c9784ce1-aef7-11e6-0000-ef37108bddb&#1;8?&#13;&#4;2016-11-17T09:02:49+01:00' xmlns:xapMM='http://ns.adobe.com/xap/1.0/mm/' xapMM:DocumentID='uuid:c9784ce1-aef7-11e6-0000-ef37108bddb&#129;v;&#159;�c&#31;&#16;'/>
<rdf:Description rdf:about='c9784ce1-aef7-11e6-0000-ef37108bddb&#1;8?&#13;&#4;2016-11-17T09:02:49+01:00' xmlns:dc='http://purl.org/dc/elements/1.1/' dc:format='application/pdf'><dc:title><rdf:Alt><rdf:li xml:lang='x-default'>Title</rdf:li></rdf:Alt></dc:title><dc:creator><rdf:Seq><rdf:li>Windows</rdf:li></rdf:Seq></dc:creator><dc:description><rdf:Seq><rdf:li>()</rdf:li></rdf:Seq></dc:description></rdf:Description>
</rdf:RDF>
</x:xmpmeta>
`
You can check it with an XML validator, entities like $#1; are not valid.
So to me the problem seem to be  the tool that generated this PDF.
