### ISSUE TITLE
looks great but doesn't do anything (!)

### ISSUE THREAD

**Issue by sandraardnas** [zaro/pdf-metadata-editor#16]
Is it because I'm running Mac OS Sierra? Very intuitive interface and the video tells me what I'd already worked out. Problem is none of the new data gets written back to the PDF. 

Am I just being blonde (?!)

**Comment by zaro** [comment]
haha, probably not :) I will  check on my mac and get back to you, but I am pretty sure it works on it.
Probably there is something else getting the the way

**Comment by gingerbeardman** [comment]
Works for me.

1. Load /Applications/PDF Metadata Editor.app
2. Open PDF
3. Change metadata
4. Press Save
5. Check modified time on PDF and changed metadata
