### ISSUE TITLE
cant change pdf producer

### ISSUE THREAD

**Issue by salmanulfarisk** [zaro/pdf-metadata-editor#2]
tried so many times to change pdf producer but its not been changed..is there any suggestions????

**Comment by zaro** [comment]
ok, I just tried editing a PDF  and Producer in both Basic and XMP PDF do change and are saved  correctly in the latest version (1.1.1) .
Can you provide some more information like the version ( you can see it in preferences window, About ).
Also is it possible to have one of the Copy Basic to XMP or Copy XMP to Basic checked in the preferences ?
