### ISSUE TITLE
Editor GUI doesn't open, though batch one does

### ISSUE THREAD

**Issue by Celtic-Knot** [zaro/pdf-metadata-editor#20]
Hello Zaro - I am trying to install on Kubuntu 18.04 with openjdk 11.0.4 2019-07-16 preinstalled. The installer jar works and installs. The batch editor opens a GUI as I would expect (and a further GUI with parameters). But the ordinary editor tries for a short while to open, then gives up. Happy to buy a license, but worried about the ordinary editor part (apparently) not working. Any help gratefully received, thank you.

**Comment by zaro** [comment]
Please try to use the new 3.0.0 version
