### ISSUE TITLE
maven dependency missing

### ISSUE THREAD

**Issue by navtis** [zaro/pdf-metadata-editor#22]
"Could not find artifact com.pretty-tools:jdde-bundle:jar:2.0.3 in central (https://repo.maven.apache.org/maven2)" (doesn't seem to be just the version, can't find any pretty-tools in maven central)

**Comment by zaro** [comment]
yes, I have no idea how to publish it to Maven Central, but here is the repo you can build it yourself:

https://github.com/zaro/jdde-bundle
