### ISSUE TITLE
suggestion: option that puts the file name into the metadata

### ISSUE THREAD

**Issue by Nichtraucher** [zaro/pdf-metadata-editor#7]
Hey,

as the title says: Perhaps an option could be added that puts the filename (except the extension) into the "title"-field?

cheers

**Comment by zaro** [comment]
Yeah, sounds useful.

The use case you have in mind is manual or automated.
What I mean by manual. Have a button or checkbox on the main screen that fills the title from the current filename.
The automated way would be an option in the settings that does this automatically  for every file that doesn't already have a title.

**Comment by Nichtraucher** [comment]
I was wondering whether having it the other way round would be useful, too: I regularly work with scientific literature and often these documents have buttlong filenames that include a lengthy title, several authors etc. To have to change these filenames by hand can be quite a nuisance.

**Comment by zaro** [comment]
If I understand you correctly the other way round is already present .

You can configure a rename template in Preferences -> General . And after that either use Save & Rename or use Batch operation -> Rename files from metadata.

**Comment by zaro** [comment]
There is {file.name} field for defaults right as of version 2.2.0.

You can put {file.name} in Title field in Defaults section in the options and when the title is missing, it will be put to the filename sans the extension.

Similarly you can use the same field in bath operations.
