### ISSUE TITLE
FileNotFoundException after "Save and rename"

### ISSUE THREAD

**Issue by awi** [zaro/pdf-metadata-editor#9]
After a "save and rename" the editor tries to reload the file which now is renamed. This yields a FileNotFound exception.

Patch (cannot attach it):

Index: src/main/java/pmedit/PDFMetadataEditWindow.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- src/main/java/pmedit/PDFMetadataEditWindow.java	(revision 69c83754ced5eb6e1341c780d8358db625322c5f)
+++ src/main/java/pmedit/PDFMetadataEditWindow.java	(revision 11570d33ea73b148d8ef4475ec9886b85bc61645)
@@ -169,6 +169,7 @@
 			File to = new File(toDir,toName);
 			try {
 				Files.move(pdfFile.toPath(), to.toPath());
+                pdfFile = to;
 			} catch (IOException e1) {
 				JOptionPane.showMessageDialog(PDFMetadataEditWindow.this,
 						"Error while renaming file:\n" + e1.toString());

**Comment by zaro** [comment]
Thank you for reporting this.
The patch was garbled and unusable, it's better to either send a pull request or send the patch as file on mail.

Just released 2.1.2 , where it is fixed.

**Comment by awi** [comment]
Sorry, you are right. I'll do it better next time.
